USE adlister_db;

DROP TABLE if EXISTS users;

DROP TABLE IF EXISTS ads;

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) UNIQUE,
  email VARCHAR(100) UNIQUE,
  password VARCHAR(100)
);

CREATE TABLE ads (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(100),
  title VARCHAR(150),
  description VARCHAR(300)
);

SHOW CREATE TABLE ads;

DESCRIBE users;

DESCRIBE ads;